### ISSUE TITLE
Need burst library!

### ISSUE THREAD

**Issue by riverstore** [sdnuacmicpc/sdnuoj#1]
Hi, 

I try to compile SDNUOJ but it need Burst. Can anyone please share the Burst library. I googled but can't find it.

Thanks a lot.

**Comment by mayswind** [comment]
@burstinair make it open-source and upload it to nuget?

**Comment by burstinair** [comment]
ok, i will make it available soon

**Comment by riverstore** [comment]
Thanks a lot :)

**Comment by riverstore** [comment]
Hi @burstinair ,

You may busy to make Burst project opensource now, can you please share the Burst dll. 
I'm sorry if my request bothering you.

Thanks a lot.

**Comment by burstinair** [comment]
Hi, @riverstore 
Burst Library is now available [here](https://github.com/burstinair/burst.net)
and you can get the dlls in path /Release

**Comment by riverstore** [comment]
Thanks a lot :+1:
